# https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll

# Handling Reading
safe:         false
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
    - jemoji
    - jekyll-paginate

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
#permalink:     pretty
permalink:     date
paginate:      5
paginate_path: "/page:num"
timezone:      null

quiet:    false
defaults: []

author_dir: author
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input:              GFM
  syntax_highlighter: rouge
  auto_ids:           false
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
